# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from jump_cloud_python_sdk.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    GRAPH = "Graph"
    PROVIDERS = "Providers"
    SYSTEM_INSIGHTS = "System Insights"
    USER_GROUPS = "User Groups"
    MANAGED_SERVICE_PROVIDER = "Managed Service Provider"
    APPLE_MDM = "Apple MDM"
    GOOGLE_EMM = "Google EMM"
    POLICIES = "Policies"
    SYSTEM_GROUPS = "System Groups"
    USERS = "Users"
    G_SUITE = "G Suite"
    OFFICE_365 = "Office 365"
    ACTIVE_DIRECTORY = "Active Directory"
    SOFTWARE_APPS = "Software Apps"
    POLICY_GROUPS = "Policy Groups"
    USER_GROUP_ASSOCIATIONS = "User Group Associations"
    SYSTEMS = "Systems"
    APPLICATIONS = "Applications"
    BULK_JOB_REQUESTS = "Bulk Job Requests"
    DUO = "Duo"
    WORKDAY_IMPORT = "Workday Import"
    LDAP_SERVERS = "LDAP Servers"
    SYSTEM_GROUP_ASSOCIATIONS = "System Group Associations"
    COMMANDS = "Commands"
    IP_LISTS = "IP Lists"
    POLICY_GROUP_TEMPLATES = "Policy Group Templates"
    AUTHENTICATION_POLICIES = "Authentication Policies"
    CUSTOM_EMAILS = "Custom Emails"
    ORGANIZATIONS = "Organizations"
    SAMBA_DOMAINS = "Samba Domains"
    ADMINISTRATORS = "Administrators"
    IDENTITY_PROVIDERS = "Identity Providers"
    INGRESSO = "Ingresso"
    POLICY_GROUP_ASSOCIATIONS = "Policy Group Associations"
    RADIUS_SERVERS = "RADIUS Servers"
    SYSTEMS_ORGANIZATION_SETTINGS = "Systems Organization Settings"
    POLICY_GROUP_MEMBERS__MEMBERSHIP = "Policy Group Members &amp; Membership"
    SYSTEM_GROUP_MEMBERS__MEMBERSHIP = "System Group Members &amp; Membership"
    USER_GROUP_MEMBERS__MEMBERSHIP = "User Group Members &amp; Membership"
    G_SUITE_IMPORT = "G Suite Import"
    PASSWORD_MANAGER = "Password Manager"
    POLICYTEMPLATES = "Policytemplates"
    PUSH_VERIFICATION = "Push Verification"
    AGGREGATED_POLICY_STATS = "Aggregated Policy Stats"
    DIRECTORIES = "Directories"
    FEATURE_TRIALS = "FeatureTrials"
    GROUPS = "Groups"
    IMAGE = "Image"
    LOGOS = "Logos"
    MICROSOFT_MDM = "Microsoft MDM"
    OFFICE_365_IMPORT = "Office 365 Import"
    SCIM_IMPORT = "SCIM Import"
    SUBSCRIPTIONS = "Subscriptions"
    FDE = "fde"
    ACCOUNT_MANAGER_CALENDAR = "AccountManagerCalendar"
    ADD_ON = "AddOn"
    APPLE_VPP = "Apple VPP"
    COMMAND_TEMPLATES = "Command Templates"
    COUNTRIES = "Countries"
    DEVICES = "Devices"
    DIRECTORY_INSIGHTS = "Directory Insights"
    DURT = "Durt"
    EDGE = "Edge"
    GO = "Go"
    KNOWLEDGE = "Knowledge"
    PARTNERS = "Partners"
    PAY_NOW = "PayNow"
    PLAN = "Plan"
    PLAN_FEATURE = "Plan Feature"
    PROMOS = "Promos"
    PUSH = "Push"
    RECOMMENDATIONS = "Recommendations"
    REMOTE_ASSIST = "Remote Assist"
    SSO = "SSO"
    SOFTWARE_CATALOG = "Software Catalog"
    SUBSCRIPTION_COMPONENT = "SubscriptionComponent"
    SUBSCRIPTION_DATA = "SubscriptionData"
    TRIAL_FEATURE_INSIGHTS = "Trial Feature Insights"
    WEB_AUTHN = "WebAuthn"
